spring:
  main:
    banner-mode: "off"
    lazy-initialization: false
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 1000
      idleTimeout: 60
      maxLifetime: 180
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: false
  cloud:
    config:
      enabled: false
server:
  http2:
    enabled: false
  port: 8080
  compression:
    enabled: true
    # Minimum response when compression will kick in
    min-response-size: 512
    # Mime types that should be compressed
    mime-types: text/xml, text/plain, application/json
  tomcat:
    connection-timeout: 500
    threads:
      max: 10
    max-connections: 10
    max-keep-alive-requests: 10
    keep-alive-timeout: 10

resilience4j:
  timelimiter:
    instances:
      project57-t1:
        timeoutDuration: 5s
        cancelRunningFuture: true
    metrics:
      enabled: true
  ratelimiter:
    instances:
      project57-r1:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0s
    metrics:
      enabled: true
  bulkhead:
    instances:
      project57-b1:
        max-concurrent-calls: 2
        max-wait-duration: 10ms
    metrics:
      enabled: true
  retry:
    instances:
      project57-y1:
        max-attempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpClientErrorException
        ignoreExceptions:
          - org.springframework.web.client.HttpServerErrorException
    metrics:
      enabled: true
  circuitbreaker:
    instances:
      project57-c1:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
    metrics:
      enabled: true

logging:
  include-application-name: false
  file:
    name: project57-app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 10GB
      max-history: 10
  level:
    root: info

management:
  endpoint:
    refresh:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
    metrics:
      enabled: true
    info:
      env:
        enabled: true
      enabled: true
    env:
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

project57:
  newFeatureFlag: false
