spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 1000
      idleTimeout: 60
      maxLifetime: 180
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  http2:
    enabled: false
  port: 8080
  compression:
    enabled: true
    # Minimum response when compression will kick in
    min-response-size: 512
    # Mime types that should be compressed
    mime-types: text/xml, text/plain, application/json
  tomcat:
    connection-timeout: 500
    threads:
      max: 10
    max-keep-alive-requests: 10
    keep-alive-timeout: 10
    max-connections: 5

resilience4j.timelimiter:
  instances:
    project57-tl:
      timeoutDuration: 5s
      cancelRunningFuture: true
