spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 1
      connectionTimeout: 1000
      idleTimeout: 60
      maxLifetime: 180
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

server:
  port: 31000
  compression:
    enabled: true
    # Minimum response when compression will kick in
    min-response-size: 512
    # Mime types that should be compressed
    mime-types: text/xml, text/plain, application/json
  tomcat:
    connection-timeout: 10
    threads:
      max: 10
    max-keep-alive-requests: 10
    keep-alive-timeout: 10
    max-connections: 5

resilience4j.timelimiter:
  instances:
    service1-tl:
      timeoutDuration: 1s
      cancelRunningFuture: true
