spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 1000
      idleTimeout: 60
      maxLifetime: 180
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  http2:
    enabled: false
  port: 8080
  compression:
    enabled: true
    # Minimum response when compression will kick in
    min-response-size: 512
    # Mime types that should be compressed
    mime-types: text/xml, text/plain, application/json
  tomcat:
    connection-timeout: 500
    threads:
      max: 10
    max-keep-alive-requests: 10
    keep-alive-timeout: 10
    max-connections: 5

resilience4j:
  timelimiter:
    instances:
      project57-t1:
        timeoutDuration: 5s
        cancelRunningFuture: true
  ratelimiter:
    instances:
      project57-r1:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0s
  bulkhead:
    instances:
      project57-b1:
        max-concurrent-calls: 2
        max-wait-duration: 10ms
logging:
  file:
    name: project57-app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 10GB
      max-history: 10
  level:
    root: info
