drop table if exists public.customer;
create table if not exists public.customer
(
    id    bigint generated by default as identity primary key,
    city  varchar(255),
    name  varchar(255),
    phone varchar(255)
);