INSERT INTO public.customer (city, name, phone) VALUES ('New York', 'Alice Johnson', '555-1234');
INSERT INTO public.customer (city, name, phone) VALUES ('Los Angeles', 'Bob Smith', '555-5678');
INSERT INTO public.customer (city, name, phone) VALUES ('Chicago', 'Carol White', '555-8765');
INSERT INTO public.customer (city, name, phone) VALUES ('Houston', 'David Brown', '555-4321');
INSERT INTO public.customer (city, name, phone) VALUES ('Phoenix', 'Eve Davis', '555-6789');
INSERT INTO public.customer (city, name, phone) VALUES ('Philadelphia', 'Frank Moore', '555-9876');
INSERT INTO public.customer (city, name, phone) VALUES ('San Antonio', 'Grace Wilson', '555-5432');
INSERT INTO public.customer (city, name, phone) VALUES ('San Diego', 'Henry Taylor', '555-7654');
INSERT INTO public.customer (city, name, phone) VALUES ('Dallas', 'Ivy Anderson', '555-2345');
INSERT INTO public.customer (city, name, phone) VALUES ('San Jose', 'Jack Thomas', '555-6543');
INSERT INTO public.customer (city, name, phone) VALUES ('San Francisco', 'Liam Martinez', '555-6781');
INSERT INTO public.customer (city, name, phone) VALUES ('Columbus', 'Olivia Garcia', '555-9823');
INSERT INTO public.customer (city, name, phone) VALUES ('Charlotte', 'Noah Rodriguez', '555-3824');
INSERT INTO public.customer (city, name, phone) VALUES ('Fort Worth', 'Emma Martinez', '555-1920');
INSERT INTO public.customer (city, name, phone) VALUES ('Detroit', 'Elijah Perez', '555-6751');
INSERT INTO public.customer (city, name, phone) VALUES ('El Paso', 'Sophia Thompson', '555-5781');
INSERT INTO public.customer (city, name, phone) VALUES ('Memphis', 'Lucas Clark', '555-3710');
INSERT INTO public.customer (city, name, phone) VALUES ('Baltimore', 'Isabella Robinson', '555-7103');
INSERT INTO public.customer (city, name, phone) VALUES ('Boston', 'Mason Walker', '555-8645');
INSERT INTO public.customer (city, name, phone) VALUES ('Milwaukee', 'Ava Lee', '555-9083');
INSERT INTO public.customer (city, name, phone) VALUES ('Denver', 'Ethan Hall', '555-6471');
INSERT INTO public.customer (city, name, phone) VALUES ('Seattle', 'Mia Young', '555-4891');
INSERT INTO public.customer (city, name, phone) VALUES ('Nashville', 'James Hernandez', '555-5743');
INSERT INTO public.customer (city, name, phone) VALUES ('Washington', 'Amelia King', '555-1239');
INSERT INTO public.customer (city, name, phone) VALUES ('Las Vegas', 'Alexander Wright', '555-3874');
INSERT INTO public.customer (city, name, phone) VALUES ('Portland', 'Charlotte Lopez', '555-7839');
INSERT INTO public.customer (city, name, phone) VALUES ('Oklahoma City', 'Benjamin Hill', '555-6745');
INSERT INTO public.customer (city, name, phone) VALUES ('Tucson', 'Harper Scott', '555-8943');
INSERT INTO public.customer (city, name, phone) VALUES ('Albuquerque', 'Sebastian Adams', '555-3748');
INSERT INTO public.customer (city, name, phone) VALUES ('Fresno', 'Evelyn Baker', '555-9284');
INSERT INTO public.customer (city, name, phone) VALUES ('Sacramento', 'William Nelson', '555-5748');
INSERT INTO public.customer (city, name, phone) VALUES ('Long Beach', 'Scarlett Carter', '555-2849');
INSERT INTO public.customer (city, name, phone) VALUES ('Kansas City', 'Joseph Allen', '555-3981');
INSERT INTO public.customer (city, name, phone) VALUES ('Mesa', 'Aria Collins', '555-7623');
INSERT INTO public.customer (city, name, phone) VALUES ('Atlanta', 'Michael Martinez', '555-7621');
INSERT INTO public.customer (city, name, phone) VALUES ('Colorado Springs', 'Ella Murphy', '555-9281');
INSERT INTO public.customer (city, name, phone) VALUES ('Virginia Beach', 'Daniel Russell', '555-7320');
INSERT INTO public.customer (city, name, phone) VALUES ('Raleigh', 'Victoria Cox', '555-6728');
INSERT INTO public.customer (city, name, phone) VALUES ('Omaha', 'Logan Mitchell', '555-8391');
INSERT INTO public.customer (city, name, phone) VALUES ('Miami', 'Grace Morgan', '555-4820');
INSERT INTO public.customer (city, name, phone) VALUES ('Oakland', 'David Jenkins', '555-8791');
INSERT INTO public.customer (city, name, phone) VALUES ('Minneapolis', 'Abigail Turner', '555-2394');
INSERT INTO public.customer (city, name, phone) VALUES ('Tulsa', 'Carter Edwards', '555-1438');
INSERT INTO public.customer (city, name, phone) VALUES ('New Orleans', 'Lily Campbell', '555-5843');
INSERT INTO public.customer (city, name, phone) VALUES ('Wichita', 'Jayden Stewart', '555-7238');
INSERT INTO public.customer (city, name, phone) VALUES ('Arlington', 'Zoe Alexander', '555-3829');
INSERT INTO public.customer (city, name, phone) VALUES ('Cleveland', 'Henry Flores', '555-2937');
INSERT INTO public.customer (city, name, phone) VALUES ('Bakersfield', 'Sofia Rivera', '555-2918');
INSERT INTO public.customer (city, name, phone) VALUES ('Tampa', 'Aiden Griffin', '555-7823');
INSERT INTO public.customer (city, name, phone) VALUES ('Honolulu', 'Avery Sullivan', '555-1983');
INSERT INTO public.customer (city, name, phone) VALUES ('Aurora', 'Matthew Alexander', '555-4567');
INSERT INTO public.customer (city, name, phone) VALUES ('Anaheim', 'Chloe Nelson', '555-3421');
INSERT INTO public.customer (city, name, phone) VALUES ('Santa Ana', 'Jack Ward', '555-7628');
INSERT INTO public.customer (city, name, phone) VALUES ('St. Louis', 'Penelope Hughes', '555-9827');
INSERT INTO public.customer (city, name, phone) VALUES ('Riverside', 'Jackson Price', '555-7682');
INSERT INTO public.customer (city, name, phone) VALUES ('Corpus Christi', 'Luna Bennett', '555-4352');
INSERT INTO public.customer (city, name, phone) VALUES ('Lexington', 'Luke Bryant', '555-1836');
INSERT INTO public.customer (city, name, phone) VALUES ('Pittsburgh', 'Savannah Torres', '555-2938');
INSERT INTO public.customer (city, name, phone) VALUES ('Anchorage', 'Wyatt Reyes', '555-8712');
INSERT INTO public.customer (city, name, phone) VALUES ('Stockton', 'Riley Cruz', '555-2913');
INSERT INTO public.customer (city, name, phone) VALUES ('Cincinnati', 'Nathaniel Hayes', '555-3983');
INSERT INTO public.customer (city, name, phone) VALUES ('Saint Paul', 'Aubrey Patterson', '555-3742');
INSERT INTO public.customer (city, name, phone) VALUES ('Newark', 'Isaiah Perez', '555-6218');
INSERT INTO public.customer (city, name, phone) VALUES ('Greensboro', 'Eleanor Powell', '555-8237');
INSERT INTO public.customer (city, name, phone) VALUES ('Buffalo', 'Ryan Howard', '555-1827');
INSERT INTO public.customer (city, name, phone) VALUES ('Plano', 'Nora Brooks', '555-3852');
INSERT INTO public.customer (city, name, phone) VALUES ('Henderson', 'Cameron Griffin', '555-9271');
INSERT INTO public.customer (city, name, phone) VALUES ('Lincoln', 'Emily Foster', '555-2389');
INSERT INTO public.customer (city, name, phone) VALUES ('Toledo', 'Julian Sanders', '555-1749');
INSERT INTO public.customer (city, name, phone) VALUES ('Orlando', 'Ariana Jenkins', '555-8762');
INSERT INTO public.customer (city, name, phone) VALUES ('Chula Vista', 'Caleb Rogers', '555-9321');
INSERT INTO public.customer (city, name, phone) VALUES ('Irvine', 'Aurora Roberts', '555-7283');
INSERT INTO public.customer (city, name, phone) VALUES ('Fort Wayne', 'Levi Patterson', '555-1837');
INSERT INTO public.customer (city, name, phone) VALUES ('Jersey City', 'Hannah Evans', '555-2938');
INSERT INTO public.customer (city, name, phone) VALUES ('Durham', 'Jonathan Wright', '555-2934');
INSERT INTO public.customer (city, name, phone) VALUES ('St. Petersburg', 'Brooklyn Gray', '555-1835');
INSERT INTO public.customer (city, name, phone) VALUES ('Laredo', 'Mateo Perry', '555-7681');
INSERT INTO public.customer (city, name, phone) VALUES ('Madison', 'Addison Ross', '555-2917');
INSERT INTO public.customer (city, name, phone) VALUES ('Chandler', 'Joshua Foster', '555-1829');
INSERT INTO public.customer (city, name, phone) VALUES ('Lubbock', 'Paisley Henderson', '555-2971');
INSERT INTO public.customer (city, name, phone) VALUES ('Scottsdale', 'Angel Rivera', '555-2987');
INSERT INTO public.customer (city, name, phone) VALUES ('Reno', 'Samantha Cox', '555-2973');
INSERT INTO public.customer (city, name, phone) VALUES ('Glendale', 'Aaron Howard', '555-9281');
INSERT INTO public.customer (city, name, phone) VALUES ('Norfolk', 'Skylar Martinez', '555-2762');
INSERT INTO public.customer (city, name, phone) VALUES ('Winston–Salem', 'Adam Jenkins', '555-9231');
INSERT INTO public.customer (city, name, phone) VALUES ('North Las Vegas', 'Hazel Stewart', '555-2638');
INSERT INTO public.customer (city, name, phone) VALUES ('Chesapeake', 'Owen Reed', '555-2916');
INSERT INTO public.customer (city, name, phone) VALUES ('Gilbert', 'Sadie Lee', '555-2738');
INSERT INTO public.customer (city, name, phone) VALUES ('Hialeah', 'Gabriel Mitchell', '555-2914');
INSERT INTO public.customer (city, name, phone) VALUES ('Garland', 'Genesis Long', '555-2371');
INSERT INTO public.customer (city, name, phone) VALUES ('Fremont', 'Nicholas Carter', '555-9283');
INSERT INTO public.customer (city, name, phone) VALUES ('Baton Rouge', 'Valentina Bell', '555-2718');
INSERT INTO public.customer (city, name, phone) VALUES ('Richmond', 'Easton Bailey', '555-2974');
INSERT INTO public.customer (city, name, phone) VALUES ('Boise', 'Paisley Watson', '555-2936');
INSERT INTO public.customer (city, name, phone) VALUES ('San Bernardino', 'Jordan White', '555-1834');
INSERT INTO public.customer (city, name, phone) VALUES ('Birmingham', 'Aurora Brooks', '555-2734');
INSERT INTO public.customer (city, name, phone) VALUES ('Spokane', 'Samuel Torres', '555-2918');
INSERT INTO public.customer (city, name, phone) VALUES ('Rochester', 'Delilah Martinez', '555-2931');
INSERT INTO public.customer (city, name, phone) VALUES ('Des Moines', 'Christopher Gonzalez', '555-9273');
INSERT INTO public.customer (city, name, phone) VALUES ('Modesto', 'Ellie Murphy', '555-9274');
INSERT INTO public.customer (city, name, phone) VALUES ('Fayetteville', 'Hunter Hill', '555-1838');
INSERT INTO public.customer (city, name, phone) VALUES ('Tacoma', 'Hailey Anderson', '555-9218');
INSERT INTO public.customer (city, name, phone) VALUES ('Shreveport', 'Jason Hernandez', '555-2932');
INSERT INTO public.customer (city, name, phone) VALUES ('Fontana', 'Leah King', '555-9275');
INSERT INTO public.customer (city, name, phone) VALUES ('Oxnard', 'Isaac Perez', '555-2378');
INSERT INTO public.customer (city, name, phone) VALUES ('Aurora', 'Stella Lee', '555-2983');
INSERT INTO public.customer (city, name, phone) VALUES ('Moreno Valley', 'Julian Diaz', '555-7291');
INSERT INTO public.customer (city, name, phone) VALUES ('Akron', 'Elliana Russell', '555-2915');
INSERT INTO public.customer (city, name, phone) VALUES ('Yonkers', 'Lucas Butler', '555-2948');
INSERT INTO public.customer (city, name, phone) VALUES ('Little Rock', 'Alyssa Foster', '555-2748');
INSERT INTO public.customer (city, name, phone) VALUES ('Amarillo', 'Brandon Brooks', '555-9238');
INSERT INTO public.customer (city, name, phone) VALUES ('Augusta', 'Paisley Rogers', '555-2731');

