apiVersion: apps/v1
kind: Deployment
metadata:
  name: project57-k8s
  labels:
    app: project57-k8s
    version: v1
spec:
  selector:
    matchLabels:
      app: project57-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: project57-k8s
    spec:
      containers:
        - name: project57
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_db
          image: project57:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 31000
            - containerPort: 32000
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "2"
              memory: "380Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: project57-service
spec:
  ports:
    - port: 31000
      targetPort: 31000
      nodePort: 31000
      name: http
    - port: 32000
      targetPort: 32000
      nodePort: 32000
      name: jvm
  selector:
    app: project57-k8s
  type: NodePort
---
